(() => {
  const STORAGE_KEY = "signalDesk.agentId";
  const el = {
    bootScreen: document.getElementById("boot-screen"), desk: document.getElementById("desk"), initForm: document.getElementById("init-form"), initSubmit: document.getElementById("init-submit"), bootError: document.getElementById("boot-error"), nameInput: document.getElementById("persona-name"), domainSelect: document.getElementById("persona-domain-select"), customDomainField: document.getElementById("custom-domain-field"), customDomainInput: document.getElementById("persona-domain-custom"), statusDot: document.getElementById("status-dot"), nameDisplay: document.getElementById("persona-name-display"), sideName: document.getElementById("side-name"), sideDomain: document.getElementById("side-domain"), domainDisplay: document.getElementById("persona-domain-display"), tagline: document.getElementById("persona-tagline"), statusValue: document.getElementById("status-value"), countdownValue: document.getElementById("countdown-value"), scheduleTime: document.getElementById("schedule-time"), scheduleStatus: document.getElementById("schedule-status"), postCountValue: document.getElementById("post-count-value"), feedCount: document.getElementById("feed-count"), agentIdValue: document.getElementById("agent-id-value"), refreshBtn: document.getElementById("refresh-btn"), resetBtn: document.getElementById("reset-btn"), feed: document.getElementById("feed"), feedEmpty: document.getElementById("feed-empty"), feedError: document.getElementById("feed-error"), cardTemplate: document.getElementById("post-card-template")
  };
  let agentId = localStorage.getItem(STORAGE_KEY), nextPublishAtMs = null, knownPostIds = new Set(), countdownTimer = null, statusTimer = null, feedTimer = null;
  init();
  function init() {
    el.domainSelect.addEventListener("change", onDomainChange); el.initForm.addEventListener("submit", onInitSubmit); el.refreshBtn.addEventListener("click", refreshAll); el.resetBtn.addEventListener("click", onReset); el.agentIdValue.addEventListener("click", copyAgentId);
    document.querySelectorAll(".nav-item").forEach(btn => btn.addEventListener("click", () => { document.querySelectorAll(".nav-item").forEach(x => x.classList.remove("active")); btn.classList.add("active"); document.getElementById(btn.dataset.target)?.scrollIntoView({ behavior: "smooth", block: "start" }); }));
    if (agentId) { showDesk(); refreshAll(); startPolling(); } else showBoot();
  }
  function onDomainChange() { const custom = el.domainSelect.value === "__custom__"; el.customDomainField.hidden = !custom; el.customDomainInput.required = custom; }
  async function onInitSubmit(e) {
    e.preventDefault(); hideError(el.bootError); const name = el.nameInput.value.trim(); const domain = el.domainSelect.value === "__custom__" ? el.customDomainInput.value.trim() : el.domainSelect.value;
    if (!name || !domain) { showError(el.bootError, "Both a name and a domain are required."); return; }
    setBusy(true);
    try { const res = await fetch("/api/agent/init", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ persona:{ name, domain }}) }); if(!res.ok){const body=await safeJson(res);throw new Error(body?.error || `Init failed (${res.status})`)} const body=await res.json(); agentId=body.agentId; localStorage.setItem(STORAGE_KEY,agentId); showDesk(); refreshAll(); startPolling(); }
    catch(err){showError(el.bootError,`Could not initialize: ${err.message}`)} finally{setBusy(false)}
  }
  function onReset(){ localStorage.removeItem(STORAGE_KEY); agentId=null; knownPostIds=new Set(); stopPolling(); el.feed.innerHTML=""; showBoot(); }
  function showBoot(){el.bootScreen.hidden=false;el.desk.hidden=true} function showDesk(){el.bootScreen.hidden=true;el.desk.hidden=false}
  function startPolling(){stopPolling();statusTimer=setInterval(fetchStatus,8000);feedTimer=setInterval(fetchFeed,12000);countdownTimer=setInterval(tickCountdown,1000)}
  function stopPolling(){[countdownTimer,statusTimer,feedTimer].forEach(t=>{if(t)clearInterval(t)});countdownTimer=statusTimer=feedTimer=null}
  async function refreshAll(){await Promise.all([fetchStatus(),fetchFeed()])}
  async function fetchStatus(){if(!agentId)return;try{const res=await fetch(`/api/agent/status?agentId=${encodeURIComponent(agentId)}`);if(res.status===404){onReset();return}if(!res.ok)throw new Error(`status ${res.status}`);const s=await res.json();el.nameDisplay.textContent=s.name||"Agent";el.sideName.textContent=s.name||"Agent";el.sideDomain.textContent=s.domain||"—";el.domainDisplay.textContent=s.domain||"—";el.tagline.textContent=s.tagline||"Discovering signals and deciding what deserves to be said.";el.postCountValue.textContent=String(s.postCount??0);el.agentIdValue.textContent=shortId(s.agentId);el.agentIdValue.title=s.agentId||"";el.statusDot.classList.remove("is-error");el.statusValue.textContent="online · autonomous";nextPublishAtMs=s.nextPublishAt?Date.parse(s.nextPublishAt):null;tickCountdown()}catch(err){el.statusDot.classList.add("is-error");el.statusValue.textContent="connection lost · retrying"}}
  function tickCountdown(){if(!nextPublishAtMs){el.countdownValue.textContent="—";el.scheduleTime.textContent="—";el.scheduleStatus.textContent="waiting";return}const rem=nextPublishAtMs-Date.now();if(rem<=0){el.countdownValue.textContent="due now";el.scheduleTime.textContent="00:00";el.scheduleStatus.textContent="due now";return}const sec=Math.floor(rem/1000),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;const short=h>0?`${h}h ${pad(m)}m`:`${pad(m)}m ${pad(s)}s`;el.countdownValue.textContent=short;el.scheduleTime.textContent=h>0?`${h}h ${pad(m)}m`:`${pad(m)}:${pad(s)}`;el.scheduleStatus.textContent="counting down"}
  async function fetchFeed(){if(!agentId)return;try{const res=await fetch(`/api/agent/feed?agentId=${encodeURIComponent(agentId)}`);if(res.status===404){onReset();return}if(!res.ok)throw new Error(`feed ${res.status}`);const body=await res.json();hideError(el.feedError);renderFeed(body.posts||[])}catch(err){showError(el.feedError,"Signal lost — retrying automatically.")}}
  function renderFeed(posts){el.feedEmpty.hidden=posts.length>0;el.feedCount.textContent=`${posts.length} ${posts.length===1?"post":"posts"}`;if(!posts.length){el.feed.innerHTML="";return}const total=posts.length,frag=document.createDocumentFragment();posts.forEach((post,i)=>{const isNew=knownPostIds.size>0&&!knownPostIds.has(post.id);frag.appendChild(buildCard(post,total-i,isNew))});el.feed.innerHTML="";el.feed.appendChild(frag);knownPostIds=new Set(posts.map(p=>p.id))}
  function buildCard(post,number,isNew){const node=el.cardTemplate.content.cloneNode(true);const card=node.querySelector(".post-card");if(isNew)card.classList.add("is-new");node.querySelector(".post-number").textContent=`TRANSMISSION ${String(number).padStart(3,"0")}`;const time=node.querySelector(".post-time"),date=new Date(post.createdAt);time.dateTime=post.createdAt;time.textContent=Number.isFinite(date.getTime())?formatTimestamp(date):post.createdAt;node.querySelector(".post-text").textContent=post.text||"";node.querySelector(".post-rationale").textContent=post.rationale||"The agent selected this signal because it cleared its editorial threshold.";const sources=node.querySelector(".post-sources");(post.sources||[]).forEach(url=>{const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.className="source-chip";a.textContent=hostnameOf(url);sources.appendChild(a)});return node}
  function shortId(id){return !id?"—":id.length>13?`${id.slice(0,8)}…${id.slice(-4)}`:id} function hostnameOf(url){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return url}} function formatTimestamp(date){return date.toISOString().replace("T"," ").slice(0,16)+" UTC"} function pad(n){return String(n).padStart(2,"0")}
  const defaultHtml=el.initSubmit.innerHTML;function setBusy(busy){el.initSubmit.disabled=busy;el.initSubmit.innerHTML=busy?"<span>Initializing…</span><b>✦</b>":defaultHtml}function showError(node,msg){node.textContent=msg;node.hidden=false}function hideError(node){node.hidden=true}async function copyAgentId(){if(!agentId)return;try{await navigator.clipboard.writeText(agentId);const prev=el.agentIdValue.textContent;el.agentIdValue.textContent="Copied ✓";setTimeout(()=>el.agentIdValue.textContent=prev,1200)}catch{}}
  async function safeJson(res){try{return await res.json()}catch{return null}}
})();
